/**
 * @file coach.service.ts
 * @module lib/growth-intelligence
 * @description
 *   Coach Engine — A deterministic, rule-based coaching layer that synthesises
 *   growth analysis, velocity, forecasting, and muscle intelligence into
 *   actionable daily and weekly briefings for the user.
 */

import type { IGrowthAnalysisSnapshot } from '@/models/GrowthAnalysisSnapshot';
import { TrendDirection, compareSnapshots } from './comparison.service';
import type { MuscleAnalysis } from './muscle-analysis.service';
import type { GrowthAnalysisResult, GrowthRecommendation } from './types';

// ─── Public Interfaces ────────────────────────────────────────────────────────

export interface DailyBrief {
  readinessScore: number;
  readinessLabel: 'Ready' | 'Recovering' | 'Fatigued';
  primaryFocus: string;
  advice: string;
}

export interface WeeklySummary {
  growthIndex: number;
  weeklyVelocity: number;
  trend: TrendDirection;
  topAchievements: string[];
  focusAreas: string[];
}

export interface TrainingReadiness {
  status: 'optimal' | 'moderate' | 'low';
  muscleReadiness: Record<string, 'ready' | 'recovering'>;
  overallRecoveryPercent: number;
}

export interface RecoveryAdvice {
  protocol: 'rest' | 'active_recovery' | 'deload' | 'normal';
  details: string;
}

export interface CoachAnalysis {
  dailyBrief: DailyBrief;
  weeklySummary: WeeklySummary;
  recommendations: GrowthRecommendation[];
  trainingReadiness: TrainingReadiness;
  recoveryAdvice: RecoveryAdvice;
}

// ─── Engine Methods ─────────────────────────────────────────────────────────

/**
 * Generates an assessment of current training readiness based on the recovery score
 * and individual muscle states.
 */
export function generateTrainingReadiness(
  result: GrowthAnalysisResult,
  muscles: MuscleAnalysis[]
): TrainingReadiness {
  const recoveryScore = result.recoveryScore.value;
  const status: 'optimal' | 'moderate' | 'low' = 
    recoveryScore >= 80 ? 'optimal' :
    recoveryScore >= 50 ? 'moderate' : 'low';
    
  const muscleReadiness: Record<string, 'ready' | 'recovering'> = {};
  for (const m of muscles) {
    muscleReadiness[m.muscle] = m.recoveryPercent >= 90 ? 'ready' : 'recovering';
  }
  
  const overallRecoveryPercent = muscles.length > 0 
    ? muscles.reduce((sum, m) => sum + m.recoveryPercent, 0) / muscles.length
    : 100; // default to fully recovered if no muscles tracked
    
  return { status, muscleReadiness, overallRecoveryPercent };
}

/**
 * Generates rule-based recovery advice derived directly from the training readiness.
 */
export function generateRecoveryAdvice(readiness: TrainingReadiness): RecoveryAdvice {
  if (readiness.status === 'low') {
    return {
      protocol: 'deload',
      details: 'Your overall recovery is critically low. Take a deload week or 2-3 full rest days to prevent overtraining.'
    };
  }
  if (readiness.status === 'moderate') {
    return {
      protocol: 'active_recovery',
      details: 'You are carrying moderate fatigue. Consider light cardio, mobility work, or an active recovery session today.'
    };
  }
  return {
    protocol: 'normal',
    details: 'You are well recovered. Proceed with your planned intense training and aim for progressive overload.'
  };
}

/**
 * Aggregates and filters recommendations from the existing engine results.
 * Can be expanded to inject muscle-specific bottleneck recommendations.
 */
export function generateRecommendations(
  result: GrowthAnalysisResult
): GrowthRecommendation[] {
  // Base recommendations generated by the primary Growth Analysis Engine
  const baseRecommendations = [...result.recommendations];
  
  // Optionally, we could map muscle bottlenecks to new GrowthRecommendations here,
  // but for Phase 5 we strictly reuse the existing analysis without duplicating logic.
  // The result.recommendations already contains highly prioritized advice.
  return baseRecommendations;
}

/**
 * Synthesizes a weekly summary from historical snapshots and velocity metrics.
 */
export function generateWeeklySummary(
  latest: IGrowthAnalysisSnapshot,
  previous: IGrowthAnalysisSnapshot | undefined,
  weeklyVelocity: number
): WeeklySummary {
  const growthIndex = latest.overallScore.value;
  let trend = TrendDirection.InsufficientData;
  const topAchievements: string[] = [];
  const focusAreas: string[] = [];
  
  if (previous) {
    const comparison = compareSnapshots(latest, previous);
    trend = comparison.overall.trend;
    
    const improvements = comparison.highlights.filter(h => h.type === 'improvement');
    const regressions = comparison.highlights.filter(h => h.type === 'regression');
    
    improvements.slice(0, 2).forEach(i => topAchievements.push(i.message));
    regressions.slice(0, 2).forEach(r => focusAreas.push(r.message));
  }
  
  // Fallbacks if comparison yields no specific highlights
  if (topAchievements.length === 0) {
    if (growthIndex >= 80) topAchievements.push('Maintained an excellent overall Growth Index.');
    else topAchievements.push('Maintained consistent training schedule.');
  }
  
  if (focusAreas.length === 0) {
    focusAreas.push('Push for progressive overload in your upcoming sessions to drive growth.');
  }
  
  return {
    growthIndex,
    weeklyVelocity,
    trend,
    topAchievements,
    focusAreas
  };
}

/**
 * Creates a focused daily brief summarizing immediate readiness and primary actionable advice.
 */
export function generateDailyBrief(
  readiness: TrainingReadiness,
  summary: WeeklySummary,
  muscles: MuscleAnalysis[]
): DailyBrief {
  const readinessScore = readiness.overallRecoveryPercent;
  const readinessLabel = 
    readiness.status === 'optimal' ? 'Ready' : 
    readiness.status === 'moderate' ? 'Recovering' : 'Fatigued';
  
  const fullyRecoveredMuscles = muscles
    .filter(m => m.recoveryPercent >= 90)
    .sort((a, b) => b.growthPotentialScore - a.growthPotentialScore)
    .map(m => m.muscle);
    
  const primaryFocus = fullyRecoveredMuscles.length > 0 
    ? `Target ${fullyRecoveredMuscles.slice(0, 2).join(' and ')} - fully recovered and primed for growth.`
    : 'Active recovery day. Allow muscles to heal before intense training.';
    
  let advice = '';
  if (readiness.status === 'low') {
    advice = 'Focus on rest, hydration, and nutrition today.';
  } else if (summary.trend === TrendDirection.Declining) {
    advice = 'Your weekly trend is declining. Ensure you are hitting your protein goals and sleeping well to reverse this trend.';
  } else if (readiness.status === 'moderate') {
    advice = 'You are partially recovered. A moderate intensity session is recommended.';
  } else {
    advice = 'You are primed for a great workout. Push for a new PR today.';
  }

  return {
    readinessScore,
    readinessLabel,
    primaryFocus,
    advice
  };
}
