import { Achievement } from './types';

export const achievements: Achievement[] = [
  // Milestones
  {
    id: 'first-workout',
    title: 'First Step',
    description: 'Complete your first workout session.',
    icon: 'Play',
    category: 'milestones',
    tier: 'bronze',
    target: 1,
    unit: 'workout',
  },
  {
    id: 'workouts-10',
    title: 'Getting Serious',
    description: 'Complete 10 workout sessions.',
    icon: 'Flame',
    category: 'milestones',
    tier: 'silver',
    target: 10,
    unit: 'workouts',
  },
  {
    id: 'workouts-50',
    title: 'Half Century',
    description: 'Complete 50 workout sessions.',
    icon: 'Medal',
    category: 'milestones',
    tier: 'gold',
    target: 50,
    unit: 'workouts',
  },
  {
    id: 'workouts-100',
    title: 'Century Club',
    description: 'Complete 100 workout sessions.',
    icon: 'Trophy',
    category: 'milestones',
    tier: 'platinum',
    target: 100,
    unit: 'workouts',
  },

  // Consistency (Streaks are harder to calculate without historical dates, we'll do simple day counts for now or we will evaluate streaks by checking dates)
  {
    id: 'streak-3',
    title: 'Momentum',
    description: 'Workout for 3 consecutive days.',
    icon: 'TrendingUp',
    category: 'consistency',
    tier: 'bronze',
    target: 3,
    unit: 'days',
  },
  {
    id: 'streak-7',
    title: 'Unstoppable',
    description: 'Workout for 7 consecutive days.',
    icon: 'Zap',
    category: 'consistency',
    tier: 'silver',
    target: 7,
    unit: 'days',
  },
  {
    id: 'streak-30',
    title: 'Iron Discipline',
    description: 'Workout for 30 consecutive days.',
    icon: 'Crown',
    category: 'consistency',
    tier: 'platinum',
    target: 30,
    unit: 'days',
  },

  // Volume (Total weight lifted)
  {
    id: 'volume-10k',
    title: 'Heavy Lifter',
    description: 'Lift a total of 10,000 kg across all workouts.',
    icon: 'Dumbbell',
    category: 'volume',
    tier: 'bronze',
    target: 10000,
    unit: 'kg',
  },
  {
    id: 'volume-100k',
    title: 'Titan',
    description: 'Lift a total of 100,000 kg across all workouts.',
    icon: 'Mountain',
    category: 'volume',
    tier: 'gold',
    target: 100000,
    unit: 'kg',
  },
  {
    id: 'volume-1m',
    title: 'Hercules',
    description: 'Lift a total of 1,000,000 kg across all workouts.',
    icon: 'Globe',
    category: 'volume',
    tier: 'platinum',
    target: 1000000,
    unit: 'kg',
  },

  // Dedication
  {
    id: 'marathon-session',
    title: 'Marathon Session',
    description: 'Complete a workout lasting more than 90 minutes.',
    icon: 'Timer',
    category: 'dedication',
    tier: 'silver',
    target: 90,
    unit: 'minutes',
  },
];
